# Generated by Django 3.1.12 on 2025-12-02 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cpr', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'CPR / ID number must be exactly 9 digits.')], verbose_name='CPR / ID number')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Mobile number must be 8 digits (without +973).')], verbose_name='Mobile number (without +973)')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNK', 'Unknown')], max_length=3)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('health_notes', models.TextField(blank=True, help_text='Optional health conditions or notes for hospitals.')),
                ('password', models.CharField(help_text='Store plain for now; later can be changed to hashed.', max_length=128)),
                ('contact_consent', models.BooleanField(default=False, help_text='Donor agrees that hospitals may contact them about requests.')),
                ('info_accuracy_confirmed', models.BooleanField(default=False, help_text='Donor confirms the information is accurate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hospital_type', models.CharField(choices=[('government', 'Government Hospital'), ('private', 'Private Hospital'), ('clinic', 'Clinic / Medical Center'), ('lab', 'Diagnostic Lab'), ('other', 'Other')], max_length=20)),
                ('licence_number', models.CharField(db_index=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'License / CR number must be exactly 8 digits.')], verbose_name='License / CR number')),
                ('city_area', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_role', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('blood_type_needed', models.CharField(max_length=3)),
                ('units', models.PositiveIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospitals.hospital')),
            ],
        ),
    ]
